!FINDING SOLUTION OF ALGEBRIC EQUATIONS BY USING GAUSS'S ELIMINATION METHOD

PROGRAM GAUSS_ELIMINATION
  IMPLICIT NONE
  REAL::AUG(100,100),TEMP,X(100)
  INTEGER::I,J,K,L,R,C

  PRINT*,"ENTER THE ROW AND COLUMN OF AUGMENTED MATRIX"
   READ*,R,C

  PRINT*,"ENTER THE ELEMENTS OF THE AUGMENTED MATRIX"
   DO I=1,R
    DO J=1,C
     READ*,AUG(I,J)
    END DO
   END DO

!NOW PERFORMING THE PROCESS TO MAKE UPPER TRAINGULAR FORM

  DO L=1,R-1
   DO I=L+1,R
     TEMP=AUG(I,L)/AUG(L,L)
     DO J=1,C
      AUG(I,J)=AUG(I,J)-TEMP*AUG(L,J)
     END DO
   END DO
  END DO
!PRINTING UPPER TRAINGULAR MATRIX

   PRINT*,"UPPER TRANGULAR MATRIX"
    DO I=1,R
     PRINT*,(AUG(I,J),J=1,C)
    END DO

DO I=1,R
 X(I)=0
END DO

!NOW SOLVE THE EQUATION FROM UPPER TRAINGULAR MATRIX
PRINT*,"YOUR'S RESULT:"
   X(R)=AUG(R,C)/AUG(R,C-1)  !LAST VALUE OF X
 PRINT*,"X(",R,") :",X(R)
  DO L=R-1,1,-1
    TEMP=0
    DO I=L+1,C-1
     TEMP = TEMP+AUG(L,I)*X(I)
      
    END DO
          
          X(L) = (AUG(L,C)-TEMP)/AUG(L,L)
     PRINT*,"X(",L,") :",X(L)
  END DO




END PROGRAM GAUSS_ELIMINATION


     






